### ISSUE TITLE
Error while running node-sass on babel6

### ISSUE THREAD

**Issue by sushant24** [xzyfer/sass-graph#77]
When running node-sass on a project using babel 6, the command fails with the following error - 

```
/mnt1/jenkins/workspace/edge-ui-all-build-deploy/node_modules/scss-tokenizer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/mnt1/jenkins/workspace/edge-ui-all-build-deploy/node_modules/scss-tokenizer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/mnt1/jenkins/workspace/edge-ui-all-build-deploy/node_modules/scss-tokenizer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/mnt1/jenkins/workspace/edge-ui-all-build-deploy/node_modules/scss-tokenizer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/mnt1/jenkins/workspace/edge-ui-all-build-deploy/node_modules/scss-tokenizer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/mnt1/jenkins/workspace/edge-ui-all-build-deploy/node_modules/scss-tokenizer/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/mnt1/jenkins/workspace/edge-ui-all-build-deploy/node_modules/scss-tokenizer/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt1/jenkins/workspace/edge-ui-all-build-deploy/node_modules/scss-tokenizer/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

It seems like the dependency scss-tokenizer is using babel5 so is unable to read the .babelrc written in the main project(which is in babel6).

Environment - 
node - 4.2.2
npm - 3.8.1

**Comment by xzyfer** [comment]
Related to #76. Thanks for the report. I've unpublished 2.2.0 for now.

**Comment by sushant24** [comment]
This is working now. Thanks a lot!!
