### ISSUE TITLE
Error: Cannot find module 'scss-tokenizer'

### ISSUE THREAD

**Issue by gianpietro1** [xzyfer/sass-graph#80]
Hi,

Over a trusty linux system (so not the latest node/npm versions, 4.8.2/4.5.0), I keep receiving the following issue when running sass-graph.js:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'scss-tokenizer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/stack/contrail/contrail-webui-third-party/node_modules/node-sass/node_modules/sass-graph/parse-imports.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

Seems like a straight forward thing and unrelated to this module, but the scss-tokenizer module is there.  I even tried installing it globally, still, parse-imports is not able to find it.

Any hint please, will be much appreciated.

Thanks.

**Comment by gianpietro1** [comment]
Never mind, for some reason, scss-tokenizer was missing index.js file.
